### ISSUE TITLE
Tempest Keep: The Eye

### ISSUE THREAD

**Issue by Xadras** [Looking4Group/L4G_Core#2327]
Complete Raid Overhaul for Tempest Keep: The Eye with Focus on Complete Groups, AIs, NPC-Values, Linking, Movement, Immunities, Visuals and Texts.

---

**ToDo:**

- 

---

- [ ] The hitpoints of all non-boss mobs has been reduced. The boss specific adds should not be affected by this change.

- [ ] The damage dealt by Novice Astromancers and Apprentice Star Scryers has been greatly reduced.
    Crystalcore Sentinels no longer Trample.
- [ ] The range of [Crimson Hand Battle Mage's](http://www.wowhead.com/npc=20047/crimson-hand-battle-mage) [Frost Bolt Volley](http://www.wowhead.com/spell=37262/frostbolt-volley) has been increased.
- [x] Astromancers and Astromancer Lords no longer use the Blast Wave ability, and the range of their Fireball Volley spells has been increased.
- [ ] The damage over time and radius of the [Star Scryer's](http://www.wowhead.com/npc=20034/star-scryer) [Starfall](http://www.wowhead.com/spell=37124/starfall) spell has been reduced.
- [ ] Arcane Resistance will prove much more effective against High Astromancer Solarian's spells.
- [ ] High Astromancer Solarian now summons fewer Solarian agents, and the Solarium Agents now deal less damage.
- [ ] The Al'ar encounter has been significantly reworked. Her movement around the room will now be more predictable, Al'ar's hit points have been reduced, and killing the Embers of Al'ar will now be both much more possible and more rewarding to the raid.
- [ ] High Astromancer Solarian's hit points have been greatly reduced.
- [ ] Reduced the radius of Fragmentation Bombs in Tempest Keep to better match their visual. 

http://wowwiki.wikia.com/wiki/Patch_2.1.0

---

- [ ] When Kael'thas Sunstrider is engaged in combat, the doors leading into his room will now properly close.

http://wowwiki.wikia.com/wiki/Patch_2.1.2

---

- [ ] Tempest Keep and Coilfang raid bosses will now all drop at least 3 items each.

- [ ] The spells cast by [High Astromancer Solarian](http://www.wowhead.com/npc=18805/high-astromancer-solarian) have been extensively reworked. Wrath of the Astromancer is a now completely different in function. Mark of the Astromancer has been renamed to Light of the Astromancer and no longer reduces Arcane resistance. A player's Arcane Resistance now also provides normal damage mitigation to Solarian's spells.
- [x] Phoenix-Hawk Hatchlings now Wing Buffet less frequently.
- [ ] Crimson Hand Centurions now deal less damage with Arcane Flurry.
- [ ] Crimson Hand Battle Mages have had their Frost Attack damage reduced.

http://wowwiki.wikia.com/wiki/Patch_2.2.0

---

- [ ] The Blood Elves that patrol the Tempest Bridge no longer patrol directly into Prince Kael'thas Sunstrider's chamber.
- [ ] All four advisors have had their health reduced by 10%.
- [ ] All of the summoned weapons have had their health reduced by 10%. 
- [ ] The ability "Meteor" has been renamed to "Dive Bomb". 
- [ ] The use of Ice Block, Divine Shield, Cloak of Shadows, and other similar spells and abilities will no longer prematurely detonate High Astromancer Solarian's Wrath of the Astromancer spell.

http://wowwiki.wikia.com/wiki/Patch_2.3.0

---

- [ ] The number of Blood Elves guarding Prince Kael'Thas' room has been reduced.

http://wowwiki.wikia.com/wiki/Patch_2.3.2

---

- [ ] The High Astromancer Solarian encounter can no longer be reset by running out of the room.
- [ ] High Astromancer Solarian now uses her ability Light of the Astromancer at a much greater frequency.
- [ ] Astromancer Lords in the packs prior to High Astromancer Solarian have gained the Domination ability.

http://wowwiki.wikia.com/wiki/Patch_2.3.2_(undocumented_changes)

---

- [ ] You may now fight Prince Kael'thas and Lady Vashj without first killing all the other bosses in their respective dungeons.

- [ ] The Vapor Clouds in the Kael'thas encounter are significantly easier to see.
- [ ] Void Reaver is now immune to Vindication again.

http://wowwiki.wikia.com/wiki/Patch_2.4.0

---

- [ ] Void Reaver no longer targets a player before casting an Arcane Orb, so Add Ons such as Deadly Boss Mods or BigWigs (AddOn) are no longer able to warn of incoming Orbs.
- [ ] Flame patches in phase 2 can no longer be killed with spell reflect by warriors. Al'ar's hit box was made smaller. 

http://wowwiki.wikia.com/wiki/Patch_2.4.0_(undocumented_changes)

---

- [ ] Arcane orbs now generate combat log entries. ***Still no combat logs as of 5/15/08***

http://wowwiki.wikia.com/wiki/Patch_2.4.2

**Comment by Xadras** [comment]
# Souces:

https://github.com/Schaka/TBC-research/issues/19

http://www.wowhead.com/zone=3845/the-eye , http://wowwiki.wikia.com/wiki/Eye_%28Tempest_Keep%29 , http://wow.gamepedia.com/Eye_(Tempest_Keep) , http://wowwiki.wikia.com/wiki/Patch_2.1.0 , http://wowwiki.wikia.com/wiki/Patch_2.2.0

http://web.archive.org/web/20100127140410/http://www.hordeguides.de/index.php?rb=19622

http://www.mmo-champion.com/threads/1623524-why-did-it-take-players-so-long-to-kill-kael-thas-sunstrider/page12 , https://enhancementshaman.wordpress.com/category/tempest-keep/

https://www.youtube.com/watch?v=X1_uLvCYkzI ,

https://www.youtube.com/watch?v=ANPVfkZAoEs

https://www.youtube.com/watch?v=49eEaKnRvz4 - Conquest - The Eye - Trash Clear

https://www.youtube.com/watch?v=3LcosmADU_0 - Paladin in Tempest Keep

https://www.youtube.com/watch?v=jMt6vjmfQo0 - Melee DPS Life on Void Reaver trash - Multiple Sawblades

https://www.youtube.com/watch?v=Gx3DWaVMP4U - Spoonizm-Tempest Keep-Void Reaver - Trash

https://www.youtube.com/watch?v=LlRT4q7AV4c - Void Reaver Resto Shaman POV @ World of Warcraft: The Burning Crusade

https://www.youtube.com/watch?v=jI5Szs_r5kQ - The Answer (Jaedenar EU) vs Void Reaver

---

https://youtu.be/wm4XsKdLNzk?t=8m40s - Al'ar

https://www.youtube.com/watch?v=it01BSGM_ko - Astromancer

http://wowwiki.wikia.com/wiki/High_Astromancer_Solarian?oldid=1192499

https://www.youtube.com/watch?v=usi9Pi27quA&t= - Twilight's Hammer vs Kael'thas Sunstrider

---

Trash: https://www.youtube.com/watch?v=C8QRGEEtc3o

https://www.youtube.com/watch?v=HmegkdKnlKY

```
#!sql

-- Netherstrand Longbow
('2126801','21268','4','0','100','2','0','0','0','0','49','1','0','0','20','0','0','0','0','0','0','0','Netherstrand Longbow - Enable Dynamic Movement and Prevent Melee on Aggro'),
('2126802','21268','9','0','100','3','0','100','4000','6000','11','36980','4','0','40','2','0','0','0','0','0','0','Netherstrand Longbow - Cast Shoot and Set Ranged Weapon Model'),
('2126803','21268','0','0','100','3','7000','11000','12000','16000','11','36979','4','0','40','2','0','0','0','0','0','0','Netherstrand Longbow - Cast Multi-Shot and Set Ranged Weapon Model'),
('2126804','21268','9','0','100','3','0','20','24000','30000','11','36994','0','1','0','0','0','0','0','0','0','0','Netherstrand Longbow - Cast Blink'),
('2126805','21268','9','0','100','3','9','80','1000','1000','49','1','0','0','0','0','0','0','0','0','0','0','Netherstrand Longbow - Enable Dynamic Movement at 9-80 Yards'),
('2126806','21268','9','0','100','3','0','8','1000','1000','49','0','0','0','20','1','0','0','40','1','0','0','Netherstrand Longbow - Disable Dynamic Movement and Enable Melee and Set Melee Weapon Model at 0-8 Yards'),
('2126807','21268','7','0','100','2','0','0','0','0','40','1','0','0','0','0','0','0','0','0','0','0','Netherstrand Longbow - Set Melee Weapon Model on Evade'),
-- Devastation
('2126901','21269','9','0','100','3','0','8','11000','15000','11','36981','0','0','0','0','0','0','0','0','0','0','Devastation - Cast Whirlwind'),
-- Cosmic Infuser
('2127001','21270','9','0','100','3','0','15','8000','12000','11','36985','0','0','0','0','0','0','0','0','0','0','Cosmic Infuser - Cast Holy Nova'),
('2127002','21270','14','0','100','3','80000','40','21000','30000','11','36983','6','1','0','0','0','0','0','0','0','0','Cosmic Infuser - Cast Heal on Friendlies'),
-- Infinity Blades
('2127101','21271','11','0','100','2','0','0','0','0','11','12787','0','0','0','0','0','0','0','0','0','0','Infinity Blades - Cast Thrash on Spawn'),
-- Warp Slicer
('2127201','21272','9','0','100','3','0','5','7000','9000','11','36991','1','0','0','0','0','0','0','0','0','0','Warp Slicer - Cast Rend'),
-- Phaseshift Bulwark
('2127301','21273','9','0','100','3','0','5','13000','17000','11','36988','1','0','0','0','0','0','0','0','0','0','Phaseshift Bulwark - Cast Shield Bash'),
-- Staff of Disintegration
('2127401','21274','4','0','100','2','0','0','0','0','49','1','0','0','22','1','0','0','0','0','0','0','Staff of Disintegration - Enable Dynamic Movement and Set Phase 1 on Aggro'),
('2127402','21274','9','5','100','3','0','100','6000','9000','11','36990','4','0','0','0','0','0','0','0','0','0','Staff of Disintegration - Cast Frostbolt (Phase 1)'),
('2127403','21274','9','5','100','3','9','80','1000','1000','49','1','0','0','0','0','0','0','0','0','0','0','Staff of Disintegration - Enable Dynamic Movement at 9-80 Yards (Phase 1)'),
('2127404','21274','9','0','100','3','0','8','1000','1000','49','0','0','0','0','0','0','0','0','0','0','0','Staff of Disintegration - Disable Dynamic Movement at 0-8 Yards'),
('2127405','21274','3','5','100','2','7','0','0','0','49','0','0','0','22','2','0','0','0','0','0','0','Staff of Disintegration - Disable Dynamic Movement and Set Phase 2 when Mana is at 7% (Phase 1)'),
('2127406','21274','3','3','100','3','100','15','1000','1000','22','1','0','0','0','0','0','0','0','0','0','0','Staff of Disintegration - Set Phase 1 when Mana is above 15% (Phase 2)'),
('2127407','21274','9','0','100','3','0','10','12000','15000','11','36989','0','1','0','0','0','0','0','0','0','0','Staff of Disintegration - Cast Frost Nova'),
('2127408','21274','7','0','100','2','0','0','0','0','22','0','0','0','0','0','0','0','0','0','0','0','Staff of Disintegration - Set Phase to 0 on Evade'),
```
